[package]
name = "chipmunk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emulator = { path = "../emulator" }
clap = { version = "4.0.29", features = ["derive"] }
sdl2 = "0.35.2"
