[package]
name = "chipmunk-backend"
version = "1.0.0"
edition = "2021"
description = "Shared, platform agnostic, backend for the chipmunk emulator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
